name: CI

on:
  workflow_dispatch:
   
      
env:
  DOCKER_USERNAME: kekgaugetswe
  REPO: kekgaugetswe/doosyapi

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        with:
        # Fetch all commits
          fetch-depth: 0
        
      - name: Sematic versioning
        id: versioning
        uses: PaulHatch/sematic-version@v4.0.2
        with: 
          branch: main
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGES"
          minor_pattern: "feat"
          format: "v${major}.${minor}.${patch}-prerealeases{increment}"
      - name: Login to Dockerhub
        uses: dokcer/login-action@v1
        with:
          username: ${{env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_USERNAME }}
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          pus: true
          tags: ${{env.REPO }}:latest,${{ env.REPO }}:${{ steps.versioning.outputs.version }}
          
      - name: Create Release
        if: ${{ !startsWith(github.ref, 'refs/tags/) }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          release_name: ${{ steps.versioning.outputs.version }}
          prerelease: true
        
          
      
      
